language: python

python:

  - "3.6"

env:

  - DJANGO=2.2

install:

  - pip install -r requirements.txt

script:

  - python3 manage.py test

before_install:

  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-get -y install sqlite3=3.8.3