# Generated by Django 2.1.7 on 2019-04-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('correct_answer_id', models.IntegerField(default=0)),
                ('question_type', models.CharField(default='mcq', max_length=200)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pass_score', models.IntegerField(default=0)),
                ('num_of_questions', models.IntegerField(default=1)),
                ('expected_duration', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuizInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('marked', models.BooleanField(default=False)),
                ('finish_time', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('questions', models.ManyToManyField(to='quiz.Question')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.SkillType'),
        ),
        migrations.AddField(
            model_name='question',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.SkillType'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.Question'),
        ),
    ]
