# Generated by Django 2.1.7 on 2019-04-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizinstance',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
