# Generated by Django 2.1.7 on 2019-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190426_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizinstance',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
