# Generated by Django 2.1.7 on 2019-04-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190318_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.SkillType'),
        ),
    ]
