# Generated by Django 2.1.7 on 2019-04-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190405_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='skill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.SkillType'),
        ),
    ]
