# Generated by Django 2.1.7 on 2019-04-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_text', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='Vacancy description', max_length=2000)),
                ('requirements', models.CharField(default='Vacancy requirments', max_length=10000)),
                ('benefits', models.CharField(max_length=500)),
                ('salary', models.IntegerField(default=1000)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Intern', 'Intern')], max_length=15)),
                ('interest_field', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_questions', to='company.Vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='vacancyanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.VacancyQuestion'),
        ),
        migrations.AddField(
            model_name='vacancyanswer',
            name='vacancy_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.VacancyApplication'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='company.VacancyQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('choice_text', 'question')},
        ),
    ]
