# Generated by Django 2.2 on 2019-04-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '__first__'),
        ('company', '0002_auto_20190428_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='interest_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.SkillType'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.JobType'),
        ),
    ]
